import os

def main():
    # Create docs directory if missing
    os.makedirs("docs", exist_ok=True)
    
    # Generate HTML content
    html = """<!DOCTYPE html>
<html>
<head><title>DevOps Greeting</title></head>
<body>
    <h1>Automated Deployment Worked!  - Vaibhav Raj</h1>
    <p>Generated by Python → GitHub Actions → GitHub Pages</p>
    <p>Insertion 1</p>
</body>
</html>"""
    
    # Write to file
    with open("docs/index.html", "w") as f:
        f.write(html)

if __name__ == "__main__":
    main()
